# config.py

NAMESPACE = "prod"
APP_LABEL = "app=cpu-hog"
DEPLOYMENT_NAME = "cpu-hog"

MODEL = "llama3"

ALLOWED_ACTIONS = [
    "INCREASE_CPU",
    "SCALE_DEPLOYMENT",
    "DO_NOTHING",
    "ESCALATE_TO_HUMAN"
]

NEW_CPU_LIMIT = "300m"

CHECK_INTERVAL = 10
RESTART_COOLDOWN = 60
CPU_THRESHOLD_PERCENT = 90